### ISSUE TITLE
Extra parameters?

### ISSUE THREAD

**Issue by omar319** [bszek213/deepCFB#6]
are there any extra parameters needed when running  `python3 collect_augment_data.py` ? when I run it I keep getting the result 
`Need data for year: []`

**Comment by bszek213** [comment]
Delete the [year_count.yaml](https://github.com/bszek213/deepCFB/blob/main/year_count.yaml) and the all of the csv files except for [all_schools.csv](https://github.com/bszek213/deepCFB/blob/main/all_schools.csv) and run again

**Comment by omar319** [comment]
I went ahead and did the above and pulled the latest and get this error::

```
Traceback (most recent call last):
  File "./deepCFB/deep_learning_multiclass.py", line 536, in <module>
    main()
  File "./deepCFB/deep_learning_multiclass.py", line 533, in main
    deepCfbMulti().run_analysis()
  File ./deepCFB/deep_learning_multiclass.py", line 528, in run_analysis
    self.test_forecast()
  File "./deepCFB/deep_learning_multiclass.py", line 342, in test_forecast
    prediction_rolling = self.dnn_class.predict(rolling_features_2)
  File "/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_filerpi81n4p.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "./python3.10/site-packages/keras/src/engine/training.py", line 2416, in predict_function  *
        return step_function(self, iterator)
    File "./python3.10/site-packages/keras/src/engine/training.py", line 2401, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "./python3.10/site-packages/keras/src/engine/training.py", line 2389, in run_step  **
        outputs = model.predict_step(data)
    File "./python3.10/site-packages/keras/src/engine/training.py", line 2357, in predict_step
        return self(x, training=False)
    File "./python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "./python3.10/site-packages/keras/src/engine/input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 10), found shape=(None, 18)
```

**Comment by omar319** [comment]
I grabbed the latest and I still get the error above running 'test'

**Comment by omar319** [comment]
Fixed
