### ISSUE TITLE
Issue running test

### ISSUE THREAD

**Issue by omar319** [bszek213/deepCFB#7]
I receive the following error running test

```
Traceback (most recent call last):
  File "./deepCFB/deep_learning_multiclass.py", line 536, in <module>
    main()
  File "./deepCFB/deep_learning_multiclass.py", line 533, in main
    deepCfbMulti().run_analysis()
  File ./deepCFB/deep_learning_multiclass.py", line 528, in run_analysis
    self.test_forecast()
  File "./deepCFB/deep_learning_multiclass.py", line 342, in test_forecast
    prediction_rolling = self.dnn_class.predict(rolling_features_2)
  File "/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_filerpi81n4p.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "./python3.10/site-packages/keras/src/engine/training.py", line 2416, in predict_function  *
        return step_function(self, iterator)
    File "./python3.10/site-packages/keras/src/engine/training.py", line 2401, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "./python3.10/site-packages/keras/src/engine/training.py", line 2389, in run_step  **
        outputs = model.predict_step(data)
    File "./python3.10/site-packages/keras/src/engine/training.py", line 2357, in predict_step
        return self(x, training=False)
    File "./python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "./python3.10/site-packages/keras/src/engine/input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 10), found shape=(None, 18)

```

**Comment by omar319** [comment]
any clue why I might still be receiving this

```
Traceback (most recent call last):
  File "./deepCFB/deep_learning_multiclass.py", line 553, in <module>
    main()
  File "./deepCFB/deep_learning_multiclass.py", line 550, in main
    deepCfbMulti().run_analysis()
  File "./deepCFB/deep_learning_multiclass.py", line 545, in run_analysis
    self.test_forecast()
  File "./deepCFB/deep_learning_multiclass.py", line 342, in test_forecast
    prediction_rolling = self.dnn_class.predict(rolling_features_2)
  File "./python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_fileug3oz1jk.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "./python3.10/site-packages/keras/src/engine/training.py", line 2416, in predict_function  *
        return step_function(self, iterator)
    File "./python3.10/site-packages/keras/src/engine/training.py", line 2401, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "./python3.10/site-packages/keras/src/engine/training.py", line 2389, in run_step  **
        outputs = model.predict_step(data)
    File "./python3.10/site-packages/keras/src/engine/training.py", line 2357, in predict_step
        return self(x, training=False)
    File "./python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "./python3.10/site-packages/keras/src/engine/input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 18), found shape=(None, 10)
```

**Comment by omar319** [comment]
Fixed
