### ISSUE TITLE
Error running two teams

### ISSUE THREAD

**Issue by omar319** [bszek213/deepCFB#8]
Error on notest when running two teams

```
Traceback (most recent call last):
  File "./deepCFB/deep_learning_multiclass.py", line 553, in <module>
    main()
  File "./deepCFB/deep_learning_multiclass.py", line 550, in main
    deepCfbMulti().run_analysis()
  File "./deepCFB/deep_learning_multiclass.py", line 547, in run_analysis
    self.predict_teams()
  File "./deepCFB/deep_learning_multiclass.py", line 429, in predict_teams
    team_1_feature_var = team_1_df.var().sum()
  File "./python3.10/site-packages/pandas/core/generic.py", line 11401, in var
    return NDFrame.var(self, axis, skipna, ddof, numeric_only, **kwargs)
  File "./lib/python3.10/site-packages/pandas/core/generic.py", line 11125, in var
    return self._stat_function_ddof(
  File "./lib/python3.10/site-packages/pandas/core/generic.py", line 11101, in _stat_function_ddof
    return self._reduce(
  File "./lib/python3.10/site-packages/pandas/core/frame.py", line 10519, in _reduce
    res = df._mgr.reduce(blk_func)
  File "./lib/python3.10/site-packages/pandas/core/internals/managers.py", line 1534, in reduce
    nbs = blk.reduce(func)
  File "./lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 339, in reduce
    result = func(self.values)
  File "./lib/python3.10/site-packages/pandas/core/frame.py", line 10482, in blk_func
    return op(values, axis=axis, skipna=skipna, **kwds)
  File "./lib/python3.10/site-packages/pandas/core/nanops.py", line 96, in _f
    return f(*args, **kwargs)
  File "./lib/python3.10/site-packages/pandas/core/nanops.py", line 158, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
  File "./lib/python3.10/site-packages/pandas/core/nanops.py", line 1007, in nanvar
    sqr = _ensure_numeric((avg - values) ** 2)
TypeError: unsupported operand type(s) for -: 'float' and 'str'
```

**Comment by bszek213** [comment]
Hi Omar, 

This issue is finally fixed with the most updated code.
